version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: challenge-1b-app
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: python src/main_1b.py
